import turtle
t=turtle.Turtle()
t.speed(1)
screen=turtle.Screen()
screen.bgpic('nani.gif')
t.begin_fill()
t.fillcolor("red")
t.left(140)
t.forward(140)
t.circle(-70,200)
t.setheading(60)
#t.left(140)
t.circle(-70,200)
t.forward(140)
t.end_fill()
t.hideturtle()
